-- creating a function for safe division
DELIMITER &&
CREATE FUNCTION SafeDiv(a INT, b INT) RETURNS FLOAT DETERMINISTIC
BEGIN
	DECLARE result FLOAT;
	IF b = 0 THEN RETURN 0;
	ELSE RETURN a / b;
	END IF;
END &&
DELIMITER ;
